// Code generated by gonverter. DO NOT EDIT.

package converter

import (
	"github.com/sivchari/gonverter/examples/simple/domain"
	"github.com/sivchari/gonverter/examples/simple/handler"
)

// ConvertUserRequestToUser converts UserRequest to User
func ConvertUserRequestToUser(src *handler.UserRequest, dst *domain.User) {
	if src == nil {
		return
	}

	ConvertUserRequestNameToUserName(src, dst)
	dst.Email = src.Email
	dst.Age = src.Age
	ConvertAddressRequestToAddress(&src.Address, &dst.Address)
}

// ConvertAddressRequestToAddress converts AddressRequest to Address
func ConvertAddressRequestToAddress(src *handler.AddressRequest, dst *domain.Address) {
	if src == nil {
		return
	}

	ConvertAddressRequestCityToAddressCity(src, dst)
	dst.ZipCode = src.ZipCode
}
