// Code generated by gonverter. DO NOT EDIT.

package slice

// ConvertTeamRequestToTeam converts TeamRequest to Team
func ConvertTeamRequestToTeam(src *TeamRequest, dst *Team) {
	if src == nil {
		return
	}

	dst.Name = src.Name
	if src.Members != nil {
		dst.Members = make([]Member, len(src.Members))
		for i := range src.Members {
			ConvertMemberRequestToMember(&src.Members[i], &dst.Members[i])
		}
	}
}

// ConvertMemberRequestToMember converts MemberRequest to Member
func ConvertMemberRequestToMember(src *MemberRequest, dst *Member) {
	if src == nil {
		return
	}

	dst.Name = src.Name
	dst.Role = src.Role
}
