// Code generated by gonverter. DO NOT EDIT.

package maptype

// ConvertConfigRequestToConfig converts ConfigRequest to Config
func ConvertConfigRequestToConfig(src *ConfigRequest, dst *Config) {
	if src == nil {
		return
	}

	dst.Name = src.Name
	if src.Settings != nil {
		dst.Settings = make(map[string]Setting, len(src.Settings))
		for k, v := range src.Settings {
			var converted Setting
			ConvertSettingRequestToSetting(&v, &converted)
			dst.Settings[k] = converted
		}
	}
}

// ConvertSettingRequestToSetting converts SettingRequest to Setting
func ConvertSettingRequestToSetting(src *SettingRequest, dst *Setting) {
	if src == nil {
		return
	}

	dst.Value = src.Value
	dst.Enabled = src.Enabled
}
