// Code generated by gonverter. DO NOT EDIT.

package pointer

// ConvertUserRequestToUser converts UserRequest to User
func ConvertUserRequestToUser(src *UserRequest, dst *User) {
	if src == nil {
		return
	}

	dst.Name = src.Name
	if src.Profile != nil {
		dst.Profile = new(Profile)
		ConvertProfileRequestToProfile(src.Profile, dst.Profile)
	}
}

// ConvertProfileRequestToProfile converts ProfileRequest to Profile
func ConvertProfileRequestToProfile(src *ProfileRequest, dst *Profile) {
	if src == nil {
		return
	}

	dst.Bio = src.Bio
	dst.Age = src.Age
}
