// Code generated by gonverter. DO NOT EDIT.

package bidirectional

// ConvertUserAPIToUserDomain converts UserAPI to UserDomain
func ConvertUserAPIToUserDomain(src *UserAPI, dst *UserDomain) {
	if src == nil {
		return
	}

	dst.ID = src.ID
	dst.FullName = src.FullName
	dst.Email = src.Email
}

// ConvertUserDomainToUserAPI converts UserDomain to UserAPI
func ConvertUserDomainToUserAPI(src *UserDomain, dst *UserAPI) {
	if src == nil {
		return
	}

	dst.ID = src.ID
	dst.FullName = src.FullName
	dst.Email = src.Email
}

// ConvertOrderAPIToOrderDomain converts OrderAPI to OrderDomain
func ConvertOrderAPIToOrderDomain(src *OrderAPI, dst *OrderDomain) {
	if src == nil {
		return
	}

	dst.OrderID = src.OrderID
	if src.Items != nil {
		dst.Items = make([]ItemDomain, len(src.Items))
		for i := range src.Items {
			ConvertItemAPIToItemDomain(&src.Items[i], &dst.Items[i])
		}
	}
}

// ConvertOrderDomainToOrderAPI converts OrderDomain to OrderAPI
func ConvertOrderDomainToOrderAPI(src *OrderDomain, dst *OrderAPI) {
	if src == nil {
		return
	}

	dst.OrderID = src.OrderID
	if src.Items != nil {
		dst.Items = make([]ItemAPI, len(src.Items))
		for i := range src.Items {
			ConvertItemDomainToItemAPI(&src.Items[i], &dst.Items[i])
		}
	}
}

// ConvertItemAPIToItemDomain converts ItemAPI to ItemDomain
func ConvertItemAPIToItemDomain(src *ItemAPI, dst *ItemDomain) {
	if src == nil {
		return
	}

	dst.Name = src.Name
	dst.Quantity = src.Quantity
}

// ConvertItemDomainToItemAPI converts ItemDomain to ItemAPI
func ConvertItemDomainToItemAPI(src *ItemDomain, dst *ItemAPI) {
	if src == nil {
		return
	}

	dst.Name = src.Name
	dst.Quantity = src.Quantity
}
