// Code generated by gonverter. DO NOT EDIT.

package nested

// ConvertUserRequestToUser converts UserRequest to User
func ConvertUserRequestToUser(src *UserRequest, dst *User) {
	if src == nil {
		return
	}

	dst.Name = src.Name
	ConvertAddressRequestToAddress(&src.Address, &dst.Address)
}

// ConvertAddressRequestToAddress converts AddressRequest to Address
func ConvertAddressRequestToAddress(src *AddressRequest, dst *Address) {
	if src == nil {
		return
	}

	dst.City = src.City
	dst.ZipCode = src.ZipCode
}
